server:
  port: ${PORT:9082}
spring:
  application:
    name: app-consumer-estoque

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      direct:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2

amqp:
  exchange: rabbitmq.test
  queue:
    estoque: queueEstoque10
    price: queuePrice10

item:
  name: name_item
  email: foo@bar.com